name = "Novus"
author = "bill3bob"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf0bab5f8d212c05c6be0ad114f71451d5581b7631ac3afe70cd81ad0141f26a"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
