name = "Novus"
author = "bill3bob"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d0cd62ea6cd1a3c8a3d7d43295859cda902fd517477fa129bb34f88f84300e4"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
