#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jun 28 20:54:25 EDT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=16
shaderPack=Sildur's Enhanced Default v1.19 Fast.zip
enableShaders=true
